### ISSUE TITLE
Improve logs when ErrorException: array_combine() in /app/app/Services/CorrelationTable.php:25

### ISSUE THREAD

**Issue by elbidone** [meumobi/AMS.Connect#100]
### Expected behaviour
Tell us what should happen

### Actual behaviour

```
[2018-01-03 12:56:17] lumen.ERROR: ErrorException: array_combine(): Both parameters should have an equal number of elements in /app/app/Services/CorrelationTable.php:25 Stack trace: #0 [internal function]: Laravel\Lumen\Application->Laravel\Lumen\Concerns\{closure}(2, 'array_combine()...', '/app/app/Servic...', 25, Array) #1 /app/app/Services/CorrelationTable.php(25): array_combine(Array, Array) #2 [internal function]: App\Services\CorrelationTable->App\Services\{closure}(Array, Array) #3 /app/app/Services/CorrelationTable.php(29): array_reduce(Array, Object(Closure), Array) #4 /app/app/Services/CorrelationTable.php(48): App\Services\CorrelationTable->__construct() #5 /app/app/Services/AMSPresenter.php(165): App\Services\CorrelationTable::getInstance() #6 /app/app/Services/AMSPresenter.php(242): App\Services\AMSPresenter->getCorrelatedFields('393178-10') #7 /app/app/Services/rubicon/RubiconPresenter.php(47): App\Services\AMSPresenter->addFields(Array) #8 [internal function]: 
```
### Steps to reproduce
1.
2.
3.

### Expected responses
- Why it happens
- How to fix it
- How to test

**Comment by elbidone** [comment]
The correlation table contains line breaks, we should be log the header and row and a comprehensive log message

**Comment by elbidone** [comment]
See `getArrayFromCsvString` from `app/Services/AMSService.php`, and improve log msg

```
[2018-01-03 14:26:12] lumen.ERROR: File Error {"exception":"array_combine(): Both parameters should have an equal number of elements"} []
```

**Comment by elbidone** [comment]
Also observed following meaning-less msg when process sublime results on `app/services/sublime/SublimeService.php`
```
[2018-01-03 15:38:19] lumen.ERROR: File Error {"exception":"array_map(): Argument #2 should be an array"} []
```

and when process unplugged results:

```
[2018-01-03 17:14:32] lumen.WARNING: Request Error {"error":"No Emails Found"} []
```
