### ISSUE TITLE
un catched error on logs when margin is badly formatted on unplugged

### ISSUE THREAD

**Issue by elbidone** [meumobi/AMS.Connect#105]
when margin is 60.00% instead of 60,00% it raises following log

```
[1:33 PM]
[2018-01-11 13:33:35] lumen.WARNING: Correlation Key Not Found {"key":"205386-889767-7038454-320*50"} []
[1:33 PM]
[2018-01-11 13:33:35] lumen.WARNING: Correlation Key Not Found {"key":"205386-889767-7038454-320*320"} []
[1:33 PM]
[2018-01-11 13:33:35] lumen.WARNING: Correlation Key Not Found {"key":"205386-889766-7038444-320*320"} []
[1:33 PM]
[2018-01-11 13:33:35] lumen.INFO: Number of Raws: 1275 [] []
[1:33 PM]
[2018-01-11 13:33:55] lumen.INFO: Job Performed: unplugged [] []
[1:33 PM]
[2018-01-11 13:33:55] lumen.ERROR: ErrorException: unlink(csvOutput1515677612.csv): No such file or directory in /app/app/Services/unplugged/UnpluggedPresenter.php:89 Stack trace: #0 [internal function]: Laravel\Lumen\Application->Laravel\Lumen\Concerns\{closure}(2, 'unlink(csvOutpu...', '/app/app/Servic...', 89, Array) #1 /app/app/Services/unplugged/UnpluggedPresenter.php(89): unlink('csvOutput151567...') #2 /app/app/Services/unplugged/UnpluggedService.php(40): App\Services\unplugged\UnpluggedPresenter->present(Array, 'd/m/Y', 'publish') #3 /app/app/Jobs/DailyReportsPublishing.php(46): App\Services\unplugged\UnpluggedService->perform(Array) #4 [internal function]: App\Jobs\DailyReportsPublishing->handle() #5
```

**Comment by elbidone** [comment]
```
[2018-01-16 11:16:44] lumen.ERROR: ErrorException: unlink(csvOutput1516101396.csv): No such file or directory in /app/app/Services/rubicon/RubiconPresenter.php:89 Stack trace: #0 [internal function]: Laravel\Lumen\Application->Laravel\Lumen\Concerns\{closure}(2, 'unlink(csvOutpu...', '/app/app/Servic...', 89, Array) #1 /app/app/Services/rubicon/RubiconPresenter.php(89): unlink('csvOutput151610...') #2 /app/app/Services/rubicon/RubiconService.php(53):
```
